const subData = [
    {
        subName: "All sub",
        subBread: "white",
        subSize: "Large",
        subToppings: ['tomatoes', 'lettuse', 'avo', 'ham', 'chesse', 'gurcins', 'onions', 'peppers', 'carrot', 'chips'],
        subSauce: ['mustard', 'bbq'],
        subDrink: "cola",
        subPrice: 249,
    },
    {
        subName: "The Baby",
        subBread: "white",
        subSize: "Small",
        subToppings: ['tomatoes', 'cucumber', 'chesse', 'chicken', 'chips'],
        subSauce: ['tomatoes sauce'],
        subDrink: "sprite",
        subPrice: 126,
    },
    {
        subName: "Crunch",
        subBread: "seeded",
        subSize: "Medium",
        subToppings: ['tomatoes', 'cucumber', 'bacon', 'meatballs', 'garlic', 'coleslaw'],
        subSauce: ['Mayo'],
        subDrink: "cola",
        subPrice: 149,
    },
    {
        subName: "MeatyMunch",
        subBread: "sour",
        subSize: "large",
        subToppings: ['ham', 'bacon', 'chesse', 'chicken', 'salami', 'steak', 'meatballs', 'coleslaw'],
        subSauce: ['bbq'],
        subDrink: "red",
        subPrice: 226,
    },
    {
        subName: "Veggie",
        subBread: "seeded",
        subSize: "small",
        subToppings: ['tomatoes', 'lettuse', 'cucumber', 'avo', 'chilles', 'carrot', 'garlic'],
        subSauce: ['musturd'],
        subDrink: "tea",
        subPrice: 151,
    },
    {
        subName: "Super Sub",
        subBread: "white",
        subSize: "large",
        subToppings: ['tomatoes', 'lettuse', 'cucumber', 'avo', 'bacon', 'chesse', 'gurcins', 'onions', 'peppers', 'pesto', 'chilles', 'carrot', 'steak', 'chips'],
        subSauce: ['mayo', 'bbq', 'sweetChillie'],
        subDrink: "cola",
        subPrice: 311,
    },
    {
        subName: "Plain and Simple",
        subBread: "white",
        subSize: "medium",
        subToppings: ['tomatoes', 'avo', 'ham', 'chesse'],
        subSauce: ['tomatoes sauce'],
        subDrink: "fanta",
        subPrice: 143,
    },
    {
        subName: "The Spicy",
        subBread: "sour",
        subSize: "small",
        subToppings: ['salami', 'pesto', 'chilles', 'chips', 'garlic', 'coleslaw'],
        subSauce: ['bbq', 'sweetChillie'],
        subDrink: "water",
        subPrice: 152,
    },
    


]
